### ISSUE TITLE
Currently, One Click does not work when getting the initial seed.

### ISSUE THREAD

**Issue by Storm-Eagle20** [wwwwwwzx/3DSRNGTool#17]
When attempting to get the Initial Seed using One Click, the console will connect, the breakpoint will be set, but 3DSRNGTool gives an error saying it failed to calibrate and to check my initial seed, despite me not having my initial seed. The same error pops up again after I reseed at the title screen in OR.

I haven't gotten to trying it with Sun yet, but unfortunately only 0.9.0 works with my Omega Ruby correctly. I can do RNG manipulation just fine with 0.9.0, only the newer versions are giving me trouble. I run Windows 7, if that makes a difference.

**Comment by wwwwwwzx** [comment]
Error code?

**Comment by Storm-Eagle20** [comment]
0x001E790C. This error displays twice, once upon setting the breakpoint, once upon reseeding at the main menu.

**Comment by wwwwwwzx** [comment]
Should be fixed, thanks. Check the lastest build on appveyor.

**Comment by Storm-Eagle20** [comment]
One Click seems to work now, but 3DSRNGTool does display some strange behavior. Firstly, it sets the breakpoint, but doesn't disconnect the system upon reseeding. PokeCalcNTR displays the seed as 00000000 even though the seed in 3DSRNGTool has successfully updated. I'm not certain if these are bugs or not.

**Comment by wwwwwwzx** [comment]
update your plugin

**Comment by Storm-Eagle20** [comment]
Alright, seems to work now, thanks.
