### ISSUE TITLE
Error when trying to use automatic calibration.

### ISSUE THREAD

**Issue by Storm-Eagle20** [wwwwwwzx/3DSRNGTool#19]
https://pastebin.com/CXNy2VBD

I attempted to use this by pressing the calibrate button when ingame, I was at Registeel and in the menu. Nothing was happening for the past 10 seconds so I had clicked stop and was going to manually calibrate. Got this error upon clicking Stop.

I am using the latest **commit** of 3DSRNGTool and the latest version of PokeCalcNTR. Also using Windows 7.

Also, would you mind adding a short explanation of when to automatically calibrate to your wiki if I did this incorrectly?

**Comment by wwwwwwzx** [comment]
Keep your console connected and use one click function beforehands.
It just use the breakpoint debug function of NTR-CFW, using identifiers to determine the timeline type and main RNG frame number when TinyMT advanced. So debugger mode is required, which is done during one click.

**Comment by Storm-Eagle20** [comment]
My console was connected and I did use one click. When I entered the game after choosing my seed through reseeding at the main menu, I was still connected and I paused the game and tried to automatically calibrate. When I stopped a few seconds later as the TinyMT was advancing and nothing was happening, I pressed Stop and got that error. That's what I was trying to say.

**Comment by wwwwwwzx** [comment]
Did you disable PSS? If you leave it on, the game will be disconnected from internet.

**Comment by Storm-Eagle20** [comment]
I never entered PSS to begin with. It causes other issues so I generally avoid going into it. Plus, I risk going into Pokemon Amie which screws with the TinyMT.

Anyways, I keep connected, use One Click, and would I keep the game paused, slowly advance while using the automatic calibration? Or do I keep it unpaused the whole time? I would like to know how to use this so I can also update my guide, since I'm /u/X-The-Komujin on reddit who made a guide for Stationary Legendaries.

One last thing, I found the cause of that bug. Basically, if you hit Calibrate, and it shows Stop, then you click on the [3] to automatically fetch the TinyMT even though it's disconnected, the NTR Helper is disconnected even though the TinyMT tool assumes it's still connected, so when you click on Stop it'll then give you that error. Perhaps that'll help you debug the issue.

**Comment by wwwwwwzx** [comment]
1) **DISABLE** PSS and stay in PSS Screen.. (If you have a experience with PKMN-NTR, you know what happened)  BTW, Amie advances too fast to do RNG, never open that....
2) TinyMT Seeds is updated during calibration, no need to update another time....
