### ISSUE TITLE
Trouble with Gen 7 egg RNG.

### ISSUE THREAD

**Issue by ForcedToRock** [wwwwwwzx/3DSRNGTool#20]
I feel like the program doesn't work with it anymore. I haven't bred anything in a Gen 7 game in over a month, and it worked just fine there. What I mean specifically is when inputting all the info and searching for the accept/reject egg count, no matter what I put, it always says to accept 194 eggs, reject 3 in the shortest path (when target frame is default at 5000). A screenshot to better illustrate.

![som](https://user-images.githubusercontent.com/10488946/30352271-194e8ed2-97ed-11e7-9f26-8415a692837a.png)

Unless I'm missing something, again it's been a while.

**Comment by wwwwwwzx** [comment]
What info did you input and what are you targeting at? 
Looks like you don't have shiny charm or parents in different language. For shininess, you should use main RNG Egg checkbox.
The accept/reject egg counts function is designed for the situation where you have the __target__ after searching and want to get to that frame quickly.

**Comment by ForcedToRock** [comment]
Ah crap, I totally forgot how it works. I don't have the shiny charm, no Masuda method, I was intending for the PID egg rng. I didn't do the target frame searching step. My mistake.
