### ISSUE TITLE
Heatran gender bugged.

### ISSUE THREAD

**Issue by Storm-Eagle20** [wwwwwwzx/3DSRNGTool#21]
Search Results: https://i.imgur.com/9Z3gcZM.jpg

Result ingame: https://i.imgur.com/uVT46Xa.png

Can't really say I can help on this as I'm not certain myself what the issue could be. But I did want to bring this up.

**Comment by wwwwwwzx** [comment]
Take Synchronize into account (set synchronizer nature and tinymt timeline
Nature doesn't need to be RNGed and gender uses 1 frame before.

**Comment by Storm-Eagle20** [comment]
I did and it didn't change. I ended up failing to catch Heatran as it unfortunately fainted with Struggle. So I went and tried again, here's the setup.

http://prntscr.com/gn8mo9

Changing the sync nature in the dropdown box has no effect.

http://prntscr.com/gn8mwc

As you can see here, I encountered that same Heatran as shown in the prntscr links and it was Female.

https://i.imgur.com/74LQSy3.png

If there's anything else I can do to help, I can, but I'm honestly not sure.

**Comment by wwwwwwzx** [comment]
Works for me. 
![](https://i.imgur.com/846Qgo9.png)
As I said. it needs your timeline input to make it a synchronize success frame
