### ISSUE TITLE
Suggestion: Allow for user to right click and copy Egg Seed when doing XY/ORAS breeding.

### ISSUE THREAD

**Issue by Storm-Eagle20** [wwwwwwzx/3DSRNGTool#26]
With the TinyMT, you can right click and copy the TinyMT in a certain box. I think it would be a good idea to allow users to right click and copy the Egg Seed when doing breeding in Gen 6. Might also help with Gen 7, but I haven't done any Gen 7 yet.

**Comment by wwwwwwzx** [comment]
Egg seeds is useless in G6. And ORAS has two Day Care => two egg seeds addresses => never know which one user is using.

**Comment by wwwwwwzx** [comment]
Already impled actually.
`Set as Current Status`
