### ISSUE TITLE
USUM To Do List

### ISSUE THREAD

**Issue by wwwwwwzx** [wwwwwwzx/3DSRNGTool#29]
Missing part:
- [x] Trainers' School Encounters
- [x] Zygarde gifts
- [x] Cosmog/Magearna Ability number
- [x] Surf Pikachu
- [x] In-game trades
- [x] Poke Pelago encounter table
- [x] Wild encounter slots table
- [x] ID RNG DB

Known issue:
- [x] Sol/Luna delay methods
- [x] UBs delay methods
- [x] Negative delay handling (Frillish)
- [x] Nature lock display for ditto five
- [x] UI for forced shiny option

**Comment by BlideTH** [comment]
Hey! I just wanted to ask if Xurkitree (stationary RNG) and Poipole (gift RNG) would be added.

**Comment by wwwwwwzx** [comment]
@BlideTH `Alola lengends`

**Comment by BlideTH** [comment]
So only for second encounter? Okay, thanks

**Comment by ForcedToRock** [comment]
I'm having trouble with Lunala. I did all the setup, but it always skips the frames. Say it's 5000 as per the timeline, moving the frames while the game is paused, I never hit that frame, like 4995, and then I'm at 5004, missing 5000.

**Comment by wwwwwwzx** [comment]
@3096 I change the color, but have no idea how it looks like on your monitor.  
@ForcedToRock Timeline 2.0 will solve this issue. https://github.com/wwwwwwzx/3DSRNGTool/commit/b7b49fa5020ec92afb0d5a6f11146189de931788

**Comment by wwwwwwzx** [comment]
Move to https://github.com/wwwwwwzx/3DSRNGTool/issues/37
