### ISSUE TITLE
Crash: System.Linq.Enumerable.FirstOrDefault<TSource>(...) returned null.

### ISSUE THREAD

**Issue by Sotam** [wwwwwwzx/3DSRNGTool#30]
Perhaps I'm a little bit too enthusiastic, but compiling the source (successfully) and then switching to the Wild RNG tab gave me a crash:

https://github.com/wwwwwwzx/3DSRNGTool/blob/4c1a9e6862c9ed19d6651c12de631e309d700a6a/3DSRNGTool/Controls/StringItem.cs#L39

System.Linq.Enumerable.FirstOrDefault<TSource>(...) returned null.

**Comment by wwwwwwzx** [comment]
Thanks
