### ISSUE TITLE
Please Add Ger Translation

### ISSUE THREAD

**Issue by Stoned13371** [wwwwwwzx/3DSRNGTool#31]
[lang_de.txt](https://github.com/wwwwwwzx/3DSRNGTool/files/1492083/lang_de.txt)
[text_Genderratio_de.txt](https://github.com/wwwwwwzx/3DSRNGTool/files/1492084/text_Genderratio_de.txt)
[text_Items_de.txt](https://github.com/wwwwwwzx/3DSRNGTool/files/1492085/text_Items_de.txt)
[text_Location_sm_de.txt](https://github.com/wwwwwwzx/3DSRNGTool/files/1492086/text_Location_sm_de.txt)
[text_Natures_de.txt](https://github.com/wwwwwwzx/3DSRNGTool/files/1492087/text_Natures_de.txt)
[text_Species_de.txt](https://github.com/wwwwwwzx/3DSRNGTool/files/1492088/text_Species_de.txt)
[text_Types_de.txt](https://github.com/wwwwwwzx/3DSRNGTool/files/1492089/text_Types_de.txt)

**Comment by wwwwwwzx** [comment]
Added. Thank you!
