### ISSUE TITLE
Wondercard RNG - Rockruff

### ISSUE THREAD

**Issue by GrimmHubber** [wwwwwwzx/3DSRNGTool#32]
I'm trying to RNG the Dusk Rockuff using 3DSRNGTool and pokecalcNTR.

I injected the wondercard in 3DSRNGTool, set up the nature and all that, I select "Safe F only" but when I do the the frame advancement with pokecalcNTR it skips the safe frame, and it has skipped a few tried now. I've been able to hit safe frames for Poipole and Type:Null consistently but not for Rockruff.

**Comment by ForcedToRock** [comment]
I was able to with Rockruff, are you at the very first Pokemon Center? Hau'oli Outskirts one by the Pokemon School? The NPC count there is 6 if you're in front of the delivery man, 4 if you're behind him.

**Comment by wwwwwwzx** [comment]
Not replicable, please join [pokeCalcNTR Discord](https://www.discord.gg/d8JuAvg) for troubleshooting.
