### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Stoned13371** [wwwwwwzx/3DSRNGTool#34]
Can you explain the fidget function? Please

**Comment by wwwwwwzx** [comment]
🤔  @Admiral-Fish

**Comment by Admiral-Fish** [comment]
You enter the frame when the player fidgets so it can adjust the timeline.

**Comment by wwwwwwzx** [comment]
https://github.com/wwwwwwzx/3DSRNGTool/wiki/Gen7-Timeline-Calibration-(PokeCalcNTR-Only)
