### ISSUE TITLE
USM ID bot problem

### ISSUE THREAD

**Issue by srwgin** [wwwwwwzx/3DSRNGTool#35]
I know the script always press A then press enter then B，loop
but I use us version US and Traditional Chinese.
player name only support 5 character，if  always press A it is error

and I use O3ds if I use mode3ntr then US then use Rosalina menu startInputRedirecion
InputRedirecion start fail
so I must run ntrmode3 first then press home run InputRedirecionmode3 then run US
which bot speed should I use？

**Comment by Stoned13371** [comment]
No. 
Start Ntrmode3 Start Game Press XY Enable Debugger than from Rosalina start Input REdirection

**Comment by srwgin** [comment]
OK Rosalina menu startInputRedirecion works now
but Traditional Chinese player name only support 5 characters
MashA name is 111111 6characters
so the bot can not continue work
is it possible let us set mashA times like blew
A x times start a b

**Comment by wwwwwwzx** [comment]
You should press `start` to active the bot, not `mashA`.
The bot is doing this loop: Press `A` (Enter !) -> Press `Enter` on the touch screen to confirm the name -> Press `B` to discard name.
I tested on my US in CHS, it works.

**Comment by srwgin** [comment]
OK it works now
thank you
