### ISSUE TITLE
Gen7 Main RNG Tool clock hands offset for USUM

### ISSUE THREAD

**Issue by AngelZodiac** [wwwwwwzx/3DSRNGTool#36]
I went ahead and recorded 9 clock hands with my seed on display with PokeCalcNTR and I couldn't get my seed from 3DSRNGTool at all, even with Ultra Moon being set as the game before opening the seed finder.

My seed was A640832C and the sequence of clock hands was 14,3,3,0,6,10,6,8,10. I double checked the sequence in SMEncounterRNGTool since you can't see the clock hands on the frames (really wish advanced would add in that functionality in 3DSRNGTool) which is offset by 1 from the sequence I got, getting a result of 13,2,2,16,5,9,5,7,9. If I use the sequence SMEncounterRNGTool gave me, I do get my seed as a result.

I actually just now noticed that every clock hand is offset by one exactly. 

For example, this looks like a 3 but is a 2 in 3DSRNGTool. I don't know about you, but that doesn't look like a 2 in 3DSRNGTool at all, maybe it's a lot easier to see the end frame of the clock in USUM compared to SM? 

![image](https://user-images.githubusercontent.com/33425108/33187517-3a5e654c-d060-11e7-9826-9e593426a2fd.png)

**Comment by wwwwwwzx** [comment]
Thank you for reporting. Now default is SuMo like (-4) and you can adjust the offset.
