### ISSUE TITLE
NTR Helper in Japanese Language

### ISSUE THREAD

**Issue by jackuma** [wwwwwwzx/3DSRNGTool#41]
When we automate the ID Bot, it does not work for Japanese language due to the difference in location of "Enter" button.

Is it possible to use "Start" Button on 3ds followed by A button instead so that it works for all languages?

**Comment by wwwwwwzx** [comment]
https://github.com/wwwwwwzx/3DSRNGTool/commit/63991b429f9d66385e04ee52c1b10a6bddcfbad0
