### ISSUE TITLE
Encounter Error 

### ISSUE THREAD

**Issue by Stoned13371** [wwwwwwzx/3DSRNGTool#42]
Route 1 (2) Night Encounter Error Try to Rng Buneary and end in a Rattata 
Route 1 (1) is Correctly

**Comment by wwwwwwzx** [comment]
Make sure you are at the right spot https://www.serebii.net/pokearth/alola/route1.shtml

**Comment by Stoned13371** [comment]
Ok i See 

But New Issue

80% of the Gender are Wrong

**Comment by wwwwwwzx** [comment]
@Stoned13371 make sure if you have synchronizer

**Comment by Stoned13371** [comment]
Synchronizer for Gender? 
Is Synchronizer not only for Nature?

**Comment by wwwwwwzx** [comment]
Synchronizer will affect the nature results and thus gender

**Comment by Stoned13371** [comment]
Ahh ok. Thanks. I Try it
