### ISSUE TITLE
Profile manager

### ISSUE THREAD

**Issue by wwwwwwzx** [wwwwwwzx/3DSRNGTool#45]
Properties to save:
- Game Version
- TSV
- ShinyCharm
- Egg Seeds

**Comment by Sotam** [comment]
I'm sort of working on this one, but not sure if you have already made progress? 'Cause it'll take me some time (work/study etc.)

**Comment by wwwwwwzx** [comment]
No progress here. I'd appreciate if you can help

**Comment by Sotam** [comment]
Awesome, I saw your commits 👍 A thing that that comes to mind is, there can be multiple profiles of 1 game. https://github.com/wwwwwwzx/3DSRNGTool/blob/9f07e41e10cd819a7ddbd6921aa19d782d094699/3DSRNGTool/MainForm.cs#L581 Perhaps we need a comboBox on the main screen where we can select the wanted profile. So, an users selects X, then we fill the combobox with possible profiles of X.

**Comment by wwwwwwzx** [comment]
Gonna do these:
- [ ] move language settings into menustrip
- [ ] Add a combobox on the top, (show description + gameversion?)
- [ ] Update profile only when change profile selection instead of clicking `Gameversion`

**Comment by wwwwwwzx** [comment]
I think it's almost done. I'm closing this
