### ISSUE TITLE
Target Frame issues with long time RNG attempts

### ISSUE THREAD

**Issue by TheDarkprophet6** [wwwwwwzx/3DSRNGTool#46]
Hello,

So, I've had issues attempting long time/frame RNGs.  I don't know an exact number for where it seems to give me issues, but, I've had issues with attempts after around 500,000 frames, where, when using the timeline function, and safe frames only, I seem to be unable to land on my seed. 

Here's a specific.  

using Safe F Only, Shiny Only, attempting Poipole on UM.
3DSRNGTool says on frame 19976314, there is a Shiny 31/31/31/30/30/31.  38 hours of waiting.
NPC Count is 5

When I get close to the frame, I pause to advance slowly to get to my frame.  I notice it is advancing at 5 frames per advancement, but, is on numbers ending in 3 and 8 instead of 4 and 9.  At one point it changes to 2 and 7, and then back to 3 and 8.  I get to my target, and land 1 frame short.

3DSRNGTool should not have given me a result of 19976314 if I can't land on that frame based on the data input when I was setting up the RNG, so i'm trying to figure out if this is something i'm doing wrong (Which, if I can get sub 500,000 frame RNGs to work consistently, I don't see how, but i'm open to there being an issue i'm causing), if this is an issue with the Tool, and issue with my 3DS (launch console), or what.  If there is any more information I can provide, please let me know.

**Comment by wwwwwwzx** [comment]
Do you remember your starting frame and did you check if the timeline match before long run?
Can't debug others procedure and according to gbatemp, several days are not a problem.

**Comment by TheDarkprophet6** [comment]
I unfortunately don't have my starting frame, but I used the Safe F Only with the initial frame with filters disabled, advanced to a frame indicated, then created a Timeline with the correct IVs I was looking for.

**Comment by TheDarkprophet6** [comment]
Ok, here's some info.  Trying the Timeline calibration.  On the latest release of 3DSRNGTool

Game: Ultra Moon
SEED: 0B438989
Initial Frame: 1963 (Safe F Only)
created timeline.  At less than 3000 frames the Timeline is off by 1 frame.  Example, 3DSRNGTool is telling me 3548, 3552, 3556, 3560, 3564, 3568.
Game is giving me: 3549, 3553, 3557, 3561, 3565, 3569

**Comment by wwwwwwzx** [comment]
Did you follow the procedure [here](https://github.com/wwwwwwzx/3DSRNGTool/wiki/Gen7-Timeline-Calibration-(PokeCalcNTR-Only)
Especially Step 1 and Step 7

**Comment by wwwwwwzx** [comment]
Try to change the standing position and make NPC count stable.

**Comment by wwwwwwzx** [comment]
Hit a frame up to 10,000,000 and timeline is stable for 19 hours without any issue.
