### ISSUE TITLE
Suggestion: Find frames for link rng based on what number pokemon is recived

### ISSUE THREAD

**Issue by LordZane** [wwwwwwzx/3DSRNGTool#5]
For registeel, you need to find a frame (x), then find a frame that advances to x (y), and then find a frame that advances to y (z). Having an option to do this automatically would be great

**Comment by wwwwwwzx** [comment]
This function only works for Pokemon Link Regis(inconstant delay), don't wanna make other part slower.
You can search and substract 09-12 frames by yourself. Sometimes multiple frames are satisified.
