### ISSUE TITLE
Seed by Clock 

### ISSUE THREAD

**Issue by Furnoz** [wwwwwwzx/3DSRNGTool#52]
I get some trouble to get my seed by ussing the clock method (I recorder my screen to have the correct input) , I get No result (Like here : https://www.youtube.com/watch?v=EOJ61KLW0fg&feature=youtu.be . https://www.youtube.com/watch?v=xLCLpgUwpeY) or I get a seed but it seem that It isn't the correct seed my party is onbecause when I took the stat of the pokemon to see how much I miss the frame, it stat did't show. Iv'e been trying to rng since 3 day and I still get the trouble, In fact I never get a seed even when by using the clock I get one seed I seem to didn't correspond with the true seed in game.

**Comment by wwwwwwzx** [comment]
This video is not avaliable

**Comment by Furnoz** [comment]
Now it should be work for the vide I put them in unlisted anyway do you know what caussing the issue about the seed did correspond to wich I found ?

**Comment by wwwwwwzx** [comment]
The pictures were captured when they begin to show up. If you are using video method, better using  `start position`. And you get the correct list, you can find your comfortable `correction`, change the box near `end position`

**Comment by Furnoz** [comment]
Yes I used the first 8 clock

**Comment by Furnoz** [comment]
9,13,9,2,8,2,16,11,12 I get this with my last try to find the seed with clock I use the start position. So I upload the video of the capture of the console.

**Comment by FedeRinhos** [comment]
Hi everybody, I am having the same problem and it's driving me absolutely crazy. Do you think it's maybe because we are playing on foreign versions? (I am playing on an italian one, you on a french one).

**Comment by FedeRinhos** [comment]
GUYS! I solved the problem and hopefully it will work for you too!

The point is, my seed works only if the number beside "End Position" is a 3, and not a 4! It changes things completely! I don't know why, perhaps it depends on the version of the game.
The way I found my number is: I tried putting in the clocks at least 10-12 times (8 or even 9 is not enough....it happend that the 9th clock didn't change the seed but the seed was wrong anyway :) ) with every number from 1 to 16, luckily I found it quickly. Now it works, I am only 3-4 frames off.

I hope this could help

**Comment by Furnoz** [comment]
I try this method but It seem to did't work

**Comment by wwwwwwzx** [comment]
Since the api use the database up to 15 clocks, so it won't parse too many inputs.
I tried local database, it gives the same results, strange..
![](https://imgur.com/mEt9Zde.png)

**Comment by FedeRinhos** [comment]
If it gives a seed with 8 clocks it means nothing. Theoretically you could type in 8 random clocks and get a seed most of the times. If it gives "no result" the following it means that the seed was wrong even before.

Just to be clear: you have to change the number BEFORE you type in the clocks. That means, you put in 0 and type the 10-12 clocks, if it gives No Result then Clear everything and then change the number to "1", and repeat the process.

**Comment by Furnoz** [comment]
So I try every possibilty to get my seed with the delay (since the delay incremate and decremant so use an excel doc to get all the possibility) ; so firt this 

4,6,4,16,13,14,4,15,15,11,16,6   : This a delay zero for the end pose / or just by using the begin pose
3,5,3,15,12,13,3,14,14,10,15,5
2,4,2,14,11,12,2,13,13,9,14,4
1,3,1,13,10,11,1,12,12,8,13,3
0,2,0,12,9,10,0,11,11,7,12,2
16,1,16,11,8,9,16,10,10,6,11,1
15,0,15,10,7,8,15,9,9,5,10,0
14,16,14,9,6,7,14,8,8,4,9,16
13,15,13,8,5,6,13,7,7,3,8,15
12,14,12,7,4,5,12,6,6,2,7,14
11,13,11,6,3,4,11,5,5,1,6,13
10,12,10,5,2,3,10,4,4,0,5,12
9,11,9,4,1,2,9,3,3,16,4,11
8,10,8,3,0,1,8,2,2,15,3,10
7,9,7,2,16,0,7,1,1,14,2,9
5,7,5,0,14,15,5,16,16,12,0,7


 I try all this possibilty and still no Result

But I give you the recording of the video and frame:

![screenshot_1](https://user-images.githubusercontent.com/34383808/33895862-c545714a-df61-11e7-80dc-8bf846f0919a.png)
![screenshot_3](https://user-images.githubusercontent.com/34383808/33895870-c863af0e-df61-11e7-8b35-98e6d2707b5d.png)
![screenshot_6](https://user-images.githubusercontent.com/34383808/33895884-cf636970-df61-11e7-94aa-c279b94af1a0.png)
![screenshot_8](https://user-images.githubusercontent.com/34383808/33895890-d1ba2556-df61-11e7-8e3e-a9ef59b1f876.png)
![screenshot_10](https://user-images.githubusercontent.com/34383808/33895896-d3c48684-df61-11e7-8c29-015c975652fe.png)
![screenshot_12](https://user-images.githubusercontent.com/34383808/33895901-d5e6daa2-df61-11e7-9f13-64d335ed0ffa.png)
![screenshot_14](https://user-images.githubusercontent.com/34383808/33895906-d8c3f598-df61-11e7-95d2-40870b422bb7.png)
![screenshot_16](https://user-images.githubusercontent.com/34383808/33895914-db02af34-df61-11e7-8f49-a1f7de45f27f.png)
![screenshot_18](https://user-images.githubusercontent.com/34383808/33895917-dde02f10-df61-11e7-8365-fb56e8306575.png)
![screenshot_20](https://user-images.githubusercontent.com/34383808/33895923-e0809e8a-df61-11e7-8da5-5ec73484d1c1.png)
![screenshot_22](https://user-images.githubusercontent.com/34383808/33895930-e26c584c-df61-11e7-878c-3004074cb2fe.png)
![screenshot_24](https://user-images.githubusercontent.com/34383808/33895934-e5325f22-df61-11e7-9c8f-7623a18a274c.png)

**Comment by wwwwwwzx** [comment]
I wonder how did you reenter the continue screen, looks like it takes longer time than mine.

**Comment by Furnoz** [comment]
Thanks you so much It work now; and sorry for this issue that isn't quite one.
