### ISSUE TITLE
The ID bot is bad.

### ISSUE THREAD

**Issue by vonKoenigsberg** [wwwwwwzx/3DSRNGTool#53]
Using a/start to advance on the keyboard screen is a really bad idea because if the network lags only once it can press a/start on the second screen and screw your seed that you resetted ages for... It happened to me after around 100 frame advances.

You should use the touchscreen on the first screen and then b on the second screen. This way it's failproof.

And if I can write such a script in PKMN-NTR you can, too.

**Comment by wwwwwwzx** [comment]
https://github.com/wwwwwwzx/3DSRNGTool/issues/41

**Comment by vonKoenigsberg** [comment]
If you want it to work with Japanese, just make a new option for it. Now the whole bot is useless because of this stupid suggestion for all regions.
