### ISSUE TITLE
USUM Shiny Rayquaza #NPC

### ISSUE THREAD

**Issue by vee4Phoenix** [wwwwwwzx/3DSRNGTool#54]
The default number of NPC while RNG-ing shiny Rayquaza is 1. I'm not sure if it's just me or not, but the number of NPC is definitely 0. I don't have pokeCalc NTR, so I found it via QR code checker.

Steps to reproduce:
1. Stationary RNG, Hoenn Legendary, Rayquaza, Jolly Sync Nature
2. Use default # of NPC which is 1
3. Stop Eontimer 3-4 seconds before target shiny frame 
4. Check current frame via QR code

Result:
It tells me I'm still 8 seconds away.

Expected Result:
I should be around 3-4 seconds away.

Current workaround:
Manually set # of NPC to 0.

**Comment by wwwwwwzx** [comment]
https://github.com/wwwwwwzx/3DSRNGTool/commit/51490cff1d5340e33ddbd7353dddfe1f9975c906
