### ISSUE TITLE
Poipole wc7 IVs read wrong

### ISSUE THREAD

**Issue by Djuraaaa** [wwwwwwzx/3DSRNGTool#62]
Hello,

I dropped the shiny Poipole .wc7 to RNG it today. The tool mistakenly read it as locked to 31s in Attack, Defense, Special Attack, Special Defense, and Speed. When I tried RNGing it ingame, it rolled a completely different spread with the usual 3 31s. I'm also using the latest commit.
![capture523](https://user-images.githubusercontent.com/24726885/36901381-eb015e50-1e61-11e8-85a8-37e601cf2352.png)
I'll submit the final results later if needed.

**Comment by wwwwwwzx** [comment]
Source code note: https://pastebin.com/bbpS6svw
