### ISSUE TITLE
Timeline Leap Calculator

### ISSUE THREAD

**Issue by wwwwwwzx** [wwwwwwzx/3DSRNGTool#63]
# Usage
Wormhole legends or event RNG with much faster frame advancing (Festival Plaza/Hau'Oli shopping mall) 🤔 
Better solution for Nihilego and Xurkitree.

# To-do list
- [ ] The calculation for last 2nd input timing
- [ ] Spread check

**Comment by Koroze23** [comment]
Nice :) Ty!
