### ISSUE TITLE
Missing Location in the 3DS RNG Tool 

### ISSUE THREAD

**Issue by Orionsilver** [wwwwwwzx/3DSRNGTool#64]
i notice in the 3DS RNG Tool it is missing a location Dividing Peak Tunnel

![missing location in the 3ds rng tool](https://user-images.githubusercontent.com/18640392/36934291-7552ff98-1f00-11e8-85a8-e1e2dd689d5b.jpg)

![missing location in the 3ds rng tool list](https://user-images.githubusercontent.com/18640392/36934305-a7b8d75a-1f00-11e8-82aa-f6edaa22d841.jpg)

missing a location Dividing Peak Tunnel is not on the list

**Comment by Orionsilver** [comment]
and another Missing location is Malie Garden for Fish location 

![missing location in the 3ds rng tool location 3](https://user-images.githubusercontent.com/18640392/36935216-7bfcfffc-1f0e-11e8-8309-7c3c7d720000.jpg)
![missing location in the 3ds rng tool location 2](https://user-images.githubusercontent.com/18640392/36935218-7c23e72a-1f0e-11e8-9abf-a5961e6445e5.jpg)

**Comment by wwwwwwzx** [comment]
Tunnel was added https://github.com/wwwwwwzx/3DSRNGTool/commit/3a5267c6cdd441cddb24c6631dcac2e745d5d57e
