### ISSUE TITLE
[Feature Request] Gen 6 Frame Search Bot

### ISSUE THREAD

**Issue by Storm-Eagle20** [wwwwwwzx/3DSRNGTool#65]
In Gen 6 you can reseed the game without having to restart NTR. I imagine a bot would be able to use this effectively to find frames for things like Friend Safari. Currently, you would have to search for frames manually which could take a long time depending on what you're searching for. But it would be possible for a bot to search for a frame automatically given the search parameters in the main RNG window, reseed if it doesn't find a result, and then pause the game when a result is found and stop the script, similar to the GSC Lua script you wrote.

If this were to be implemented, it would make for an extremely easy way to search for high IV or Hidden Power frames for Mystery Gift, Friend Safari, and Wild encounters. The framework already exists as there's an ID bot and 3DSRNGTool can already automatically detect when the seed changes.

Would you be willing to implement a feature similar to this?

**Comment by wwwwwwzx** [comment]
Not related to RNG process and might not be allowed in ptrades.
I‘ve already done this in another repo for RNG bots but it won't be public for now.
You can fork this repo and write the bot logic like this, it should be very simple.
https://github.com/wwwwwwzx/3DSRNGTool/blob/34222b1291bfaecabaf5a67f8e28e2d2937c8964/3DSRNGTool/Subforms/NTRHelper.cs#L165-L191
