### ISSUE TITLE
# Of Perfect IVs >=3 Is Hiding Good Spreads

### ISSUE THREAD

**Issue by tacocat777** [wwwwwwzx/3DSRNGTool#66]
I was trying to look for spreads for my OCT2014 Diance (non-glitched) on AS and I noticed when I had # Of Perfect IVs set to >=3, I was finding little to no spreads after multiple resets.

When I set it to 0 and input iv ranges for each individual stat it worked fine (and I instantly found like two perfect spreads like 6 min away).

**Comment by wwwwwwzx** [comment]
Not an issue. Just luck

**Comment by tacocat777** [comment]
I can reproduce, the issue and so you if you want.

**Comment by tacocat777** [comment]
I didn't reset and just randomly find a spread using same method. 

I noticed something was up around my 8-9th reset of finding absolutely 0 spreads (I was only looking for 4ivs on a Pokemon w/ 3 confirmed 31s..). Then (on the same seed) I decided to try and set # Of Perfect IVs set = 0.

**Comment by wwwwwwzx** [comment]
Screenshots thanks
