### ISSUE TITLE
TID SID RNG in gen 7

### ISSUE THREAD

**Issue by WyrXIII** [wwwwwwzx/3DSRNGTool#68]
The purpose of this would be to nickname specific events (Requires TID SID OT and Gender to match the event to nickname it)

Currently in order for TID SID RNG to match a specific event in gen 7 you have to look for a specific TID or SID and scroll through thousands of results to hopefully find something that matches 1 event at a time, which is terribly inefficient if you're fine with matching any from a list of events.

My suggestion instead is that you can either import or add multiple TID / SID combinations and have the 3ds tool output frames which has the frames with both TID SID. If this wasn't clear please let me know and I'll try to clarify it further. Thanks

**Comment by wwwwwwzx** [comment]
You can use `Current Seed` and `Regular Expression` to do so.
For example, Ash's Original Cap Pikachu
TID: 42450 => 0xa5d2
SID: 09568 => 0x2560
So add one line `2560A5D2$`  to `Current Seed` for searching this events

**Comment by WyrXIII** [comment]
http://prntscr.com/itj3wj it hasn't been affecting my results to change the Current Seed. And this will allow me to input multiple events at a time into "Current Seed" so I can try to hit an array of specific event pokemon?

**Comment by WyrXIII** [comment]
http://prntscr.com/itkhh4 it still pulls every result with the TID box blank, is RegEx supposed to be unchecked? Just wanted to know what the course of action was supposed to be. Thanks for the quick replies.

**Comment by wwwwwwzx** [comment]
Try the [build](https://ci.appveyor.com/project/wwwwwwzx/3dsrngtool) on Appveyor.
