### ISSUE TITLE
TinyMT Tool: Setting as Current Status causes exception error.

### ISSUE THREAD

**Issue by Storm-Eagle20** [wwwwwwzx/3DSRNGTool#69]
https://i.imgur.com/Cv63Wul.png

Right clicking a TinyMT frame and setting it as the current one causes an exception error.

**Comment by wwwwwwzx** [comment]
was fixed https://github.com/wwwwwwzx/3DSRNGTool/commit/bafea9b2b5aa7c9b98bba4509fefe80b9279a8f9#diff-cd873d8a12421ae131dd14753126b420R193
