### ISSUE TITLE
Gen 6 Zoroark Wondercard Importing

### ISSUE THREAD

**Issue by Storm-Eagle20** [wwwwwwzx/3DSRNGTool#7]
https://www.dropbox.com/s/w5alwuxsqoex85t/556%20-%20It%27s%20a%20Zoroark%20full%20of%20tricks%21.wc6?dl=0

My Sludge Bomb Zoroark .WC6 isn't importing correctly. I managed to RNG it by setting the flags manually, but I think there might be a bug with the 3DSRNGTool as it's not importing this .WC6 file. An error is displayed upon importing it. I believe the cause *might* be due to gender lock, which is extremely rare for events. This issue may apply to other events, but I can't say what the issue might be.

As a note, this was exported using PKHeX out of a 'main' file using JK's Save Manager.

**Comment by wwwwwwzx** [comment]
I also got an exception when I import your wc into PKHeX and click the gender.
Wondercards from projectpokemon.org have gender value 0x00 and 0x01, but yours got 0x02 which means fixed genderless.
But I know why it can't be imported, fix soon.
