### ISSUE TITLE
about searching and QR-using frame

### ISSUE THREAD

**Issue by So-rei** [wwwwwwzx/3DSRNGTool#70]
I added this probs last month.
https://www.axfc.net/u/3905057.rar (when i used 3DSRNGTool(1.0.0))

prob 1:
When I tried timer place, but frequently missed it... XD
 then i added "about" first seed searching.
"about" searched, try to search (selected timer place + before timer place).
It is natural, 8 timers not enough to find specific seed. about need to 11~13 timers.

prob 2:
I found to check "Safe F Only", focused Frame is just "?" or not.
then i changed focused Frame and any Frame(<-Display config added).

prob 3:
In addition, divide QR-using frame and Timer-using it.

Maybe any players tried that flow....
//1. Pushed A to adjustment frame in QR-menu display
//2. QR-menu display close
//3. Return main-menu display
//4. Main-menu display close
//5. Return neutral
//6. Encountered Pokemon !

While 2 to 3, I called QR-using frame.
that frame d'nt have neutral background, so NPC never appear and Player own never marked.
 When 3 to 6, Timer-using frame.

I  measured QR-using frame by Rayquaza, and include this exe const value (=15).

**Comment by Real96** [comment]
> I added this probs last month. https://www.axfc.net/u/3905057.rar (when i used 3DSRNGTool(1.0.0))
> 
> prob 1: When I tried timer place, but frequently missed it... XD then i added "about" first seed searching. "about" searched, try to search (selected timer place + before timer place). It is natural, 8 timers not enough to find specific seed. about need to 11~13 timers.
> 
> prob 2: I found to check "Safe F Only", focused Frame is just "?" or not. then i changed focused Frame and any Frame(<-Display config added).
> 
> prob 3: In addition, divide QR-using frame and Timer-using it.
> 
> Maybe any players tried that flow.... //1. Pushed A to adjustment frame in QR-menu display //2. QR-menu display close //3. Return main-menu display //4. Main-menu display close //5. Return neutral //6. Encountered Pokemon !
> 
> While 2 to 3, I called QR-using frame. that frame d'nt have neutral background, so NPC never appear and Player own never marked. When 3 to 6, Timer-using frame.
> 
> I measured QR-using frame by Rayquaza, and include this exe const value (=15).

Doesn't seem an issue, pls explain it better and i'll reopen in case
