### ISSUE TITLE
Strange error.

### ISSUE THREAD

**Issue by Storm-Eagle20** [wwwwwwzx/3DSRNGTool#71]
https://i.imgur.com/1QhNEgU.png

After doing the timeline leap, clicking no to check the spread, clicking calculate again, and then scrolling the results makes the program endlessly throw out errors. Not sure of the cause and can't check myself as my Visual Basic trial has expired and I don't intend on cracking it.

**Comment by Real96** [comment]
Seems it is fixed now, cause i can't replicate.

![image](https://user-images.githubusercontent.com/20956021/141651778-ae6665cc-d016-4b86-b4d6-dc08514f586b.png)

Closing, in case i'll reopen.
