### ISSUE TITLE
Crash when searching around specific target frames

### ISSUE THREAD

**Issue by AndSlg** [wwwwwwzx/3DSRNGTool#74]
I was trying to RNG Stakataka and there is a set of frames that when used as the target frame will crash the application.

[3dsrngtool setup](https://i.imgur.com/7Ij09iS.png)

Setting frames 82024-82027 as the Target Frame and performing a search around target will cause the app to keep allocating memory non-stop and stop responding so I have to terminate it.

**Comment by Real96** [comment]
Seems it is fixed now, cause i can't replicate.

![image](https://user-images.githubusercontent.com/20956021/141650951-3a1cdd62-555c-44ba-9102-49d35f7ae9ef.png)

Closing, in case i'll reopen.
