### ISSUE TITLE
Is capture rng possible yet?

### ISSUE THREAD

**Issue by Inkblot777** [wwwwwwzx/3DSRNGTool#76]
Sorry this isn't really an issue. I just wasn't sure where to ask this. I know a WIP of capture rng is in the program at the moment (where you rng if a pokemon will be caught with a pokeball). I was wondering if it is possible to do it with what is available now? it at least seems to be able to be functional enough to do it. I have attempted to try it, but seem to have an issue with figuring out what the delay between throwing a pokeball and when it actually calculates capture. Anyway, I was just wondering if it is possible at all, and if so, is there any guide/way to do it?

Again, sorry this isn't an issue. I have been asking around about this, and people have told me to ask you since you created the program. I wasn't sure how to do that so I came here. Sorry if i am being a bother.

**Comment by Real96** [comment]
Yes it is now possible. Come to PokemonRNG channel to ask how to do this!
