### ISSUE TITLE
What should I do when the question,“The underlying connection was closed: An unexpected error occurred on a send.”,happened?

### ISSUE THREAD

**Issue by wzh199633** [wwwwwwzx/3DSRNGTool#77]
![image](https://user-images.githubusercontent.com/37525488/46898282-c5a58c80-ceba-11e8-8cbf-c004dff46ddf.png)

**Comment by Sotam** [comment]
IIRC, this method requires an external webservice. I guess that service is down..

**Comment by Real96** [comment]
Seems it is fixed now, cause i can't replicate.

![image](https://user-images.githubusercontent.com/20956021/141650722-19ce362a-0068-4d5b-b05c-8d217f4f517b.png)


Closing, in case i'll reopen.
