### ISSUE TITLE
Convert the program for Mac OS?

### ISSUE THREAD

**Issue by demonfire11** [wwwwwwzx/3DSRNGTool#78]

**Comment by Admiral-Fish** [comment]
Can run it on mac using wine.

https://www.reddit.com/r/pokemonrng/comments/7f0qu3/running_3dsrngtool_on_mac_and_linux/

**Comment by chaseadams509** [comment]
Wine has broke 32bit support, and thus 3DSRNGTool can no longer work with wine. Could this issue be reopened?

```
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Internal error.
```
