### ISSUE TITLE
ORAS freezes when connecting with 1.0.4

### ISSUE THREAD

**Issue by HDeDeDe** [wwwwwwzx/3DSRNGTool#80]
When I try to connect to my copy of Omega Ruby on the latest version of 3DSRNGTool, the game never proceeds past frame 0. The system doesn't seem to crash however, as the NTR menu and Rosalina menu both still work, though a reboot is required to get back to the home menu. When using version 1.0.3 of 3DSRNGTools, the game starts just fine.
Using New 3DS, Luma3DS 10.0.1 and NTR 3.6.1 on firmware 11.13.0-45U if that helps.

**Comment by istratos** [comment]
+1 to this issue. The same exact thing is happening to me as described.
Version 1.0.4
Firmware 11.13.0-45U
Old 3DS
Luma3DS is 10.0.1
NTR 3.6.1

**Comment by solloron1** [comment]
I get the samething. I downgraded my Luma (not sure I had to) and I grabbed 1.0.3. And the NTR helper works as intended.
