### ISSUE TITLE
Crashing when calculating shortest path for low frame egg

### ISSUE THREAD

**Issue by karekanol13** [wwwwwwzx/3DSRNGTool#81]
I've gotten the normal egg rng to work for me one time, but no matter how low I go for my target frames, if I try to go for a shiny the tool gets stuck loading forever and I'm forced to close it. Tried hitting 30 frames most recently thinking it would be quick but still froze the program. The frames in the program show up as light blue to indicate shinyness I'm guessing, but the Frame Advance field is blank for all shinies.

**Comment by xuleta** [comment]
I've been able to consistently replicate the crash using the following parameters:

[3] CAD0F413
[2] 7FB04B7A
[1] 28175ED2
[0] 778B28C7
TSV 1216
Masuda Method checked
Target Frame 174
Shortest Path selected.

Application always freezes when I click on Calculate using the parameters above.

It won't freeze with either a different seed, different TSV or if Masuda Method is unchecked.

<img width="1224" alt="Captura de Tela 2020-04-01 às 09 49 44" src="https://user-images.githubusercontent.com/39951364/78138997-2ea9f880-73fe-11ea-8da6-6095a459960f.png">
