### ISSUE TITLE
3DSRNGTool keeps on freezing when I type in the seed

### ISSUE THREAD

**Issue by Deadfalt999** [wwwwwwzx/3DSRNGTool#86]
I'm on the latest version of 3DSRNGTool and it just keeps on freezing everytime I enter the seed I get in PCalc.

**Comment by Real96** [comment]
> I'm on the latest version of 3DSRNGTool and it just keeps on freezing everytime I enter the seed I get in PCalc.

Can you explain exactly what happens?

**Comment by Real96** [comment]
Closing this cause can't replicate. I'll reopen in case.
