### ISSUE TITLE
Problems with Ubuntu/Wine

### ISSUE THREAD

**Issue by dpgexe** [wwwwwwzx/3DSRNGTool#87]
Hello, I tried to follow the [guide](https://www.reddit.com/r/pokemonrng/comments/7f0qu3/running_3dsrngtool_on_mac_and_linux/) in Reddit to use this software in Linux/Ubuntu. I installed everything and did everything, but when I try to run it using `wine 3DSRNGTool.exe` my terminal returns this error `0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed`. I'm currently using Lubuntu 20.04 with kernel 5.8.0-50-generic, also using wine-5.0.

It would be nice if there were compilation instructions for Ubuntu. Thank you!

**Comment by Real96** [comment]
Never used it on Linux, but anyway: https://www.dedoimedo.com/computers/wine-dotnet-mono.html
