### ISSUE TITLE
Cant launch 3DSRNGtool

### ISSUE THREAD

**Issue by OathBreaker1** [wwwwwwzx/3DSRNGTool#88]
Hello, I am new to RNG manipulation and I've gotten everything ready and the last obstacle is the 3DSRNGtool which will not launch on my computer (Windows 7). When the application is downloaded and selected it says "3DSRNGtool has stopped working" I can't find any solutions online and I'm not sure how to fix this. I've tried following the protocol in task manager while also trying every version of 3DSRNGtool to no avail.

**Comment by Real96** [comment]
Do you have .Net installed?

**Comment by OathBreaker1** [comment]
I ended up fixing it on my own, it was so long ago I don’t exactly remember what it was. If I recall correctly I was missing some sort of update to my computers properties that I had to download on the windows website.
