### ISSUE TITLE
ntr工具用不了

### ISSUE THREAD

**Issue by RedicalRed** [wwwwwwzx/3DSRNGTool#95]
大佬你好，打扰了，我想用3ds乱数工具乱人物id，用那个ntr工具连接不了老2ds，地址和fbi里面查看到的地址也是输的一样，就是连接不了。显示unable to connect the console，求求大佬指点一下

**Comment by Real96** [comment]
> 大佬你好，打扰了，我想用3ds乱数工具乱人物id，用那个ntr工具连接不了老2ds，地址和fbi里面查看到的地址也是输的一样，就是连接不了。显示unable to connect the console，求求大佬指点一下

Pls write in english, i can't speak chinese

**Comment by RedicalRed** [comment]
> > 大佬你好，打扰了，我想用3ds乱数工具乱人物id，用那个ntr工具连接不了老2ds，地址和fbi里面查看到的地址也是输的一样，就是连接不了。显示unable to connect the console，求求大佬指点一下
> 
> Pls write in english, i can't speak chinese

Sorry，haha，I have solved the problems，thanks you，my English is not very well.

**Comment by Real96** [comment]
> > > 大佬你好，打扰了，我想用3ds乱数工具乱人物id，用那个ntr工具连接不了老2ds，地址和fbi里面查看到的地址也是输的一样，就是连接不了。显示unable to connect the console，求求大佬指点一下
> > 
> > 
> > Pls write in english, i can't speak chinese
> 
> Sorry，haha，I have solved the problems，thanks you，my English is not very well.

Don't worry and thanks for the feedback!
