### ISSUE TITLE
Ntr gets connected to Pokémon Y but then Game crashes

### ISSUE THREAD

**Issue by VeloNewNew** [wwwwwwzx/3DSRNGTool#99]
![IMG_20240728_181934](https://github.com/user-attachments/assets/80ad2805-5d2a-4f15-afa4-6eb5a804c1b6)
[crash_dump_00000003.dmp](https://github.com/user-attachments/files/16404545/crash_dump_00000003.dmp)

**Comment by Real96** [comment]
I suggest to switch to [PokeReader](https://github.com/zaksabeast/PokeReader). It is more updated and the connection feature is no more necessary

**Comment by VeloNewNew** [comment]
Nvm man i forgor to install that plugin
